### ISSUE TITLE
How to obtain the MQTT message id

### ISSUE THREAD

**Issue by runjava** [rabbitmq/rabbitmq-mqtt#130]
![image](https://cloud.githubusercontent.com/assets/13701232/23822025/797f5b02-067e-11e7-9848-f89ba67adc85.png)

Message ID 10

![image](https://cloud.githubusercontent.com/assets/13701232/23822034/926173ee-067e-11e7-8150-497420f5d748.png)

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](groups.google.com/forum/#!forum/rabbitmq-users). Thank you.
