### ISSUE TITLE
Support retain flag

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-mqtt#16]
We've seen enough requests for `RETAIN` to be supported.

A high profile user N wants to store retained messages in Cassandra. It makes sense to make the initial implementation to store messages in RAM (possibly with a TTL).

**Comment by Hades32** [comment]
We're using RETAINED in an IoT scenario where we store small configs on special topics. So having retained messages being persistent would be pretty important in our scenario.

**Comment by michaelklishin** [comment]
@Hades32 yes, we recognise that. There are many ways to store retained messages in a durable, since the problem boils down to a key/value store. If we can come up with an on-disk implementation that satisfies us, we'll ship one in the plugin. If not, developing a LevelDB, HanoidDB, Riak, Cassandra-based implementations should be straightforward.

**Comment by michaelklishin** [comment]
The MQTT 3.1.1 spec does not really clarify what the consistency expectations are for retained messages in a cluster environment.

We will make this store pluggable but can't ignore that we need to have a default implementation and
the fact that our team is currently 2 engineers.

Currently I'm inclined to provide a "node local" implementation by default and marking the feature "development quality" in the docs. Larger users can bring their own implementation, e.g. on top of Riak or Cassandra. Not a great solution but would let customer N proceed with their implementation, provide those who need retained message an interface they can implement, and not tie a half of our team for weeks or months to produce a more complete implementation (based on riak_core, for example).

**Comment by michaelklishin** [comment]
FTR, the user N is OK with the above strategy (shipping only a node-local implementation by default but establishing a common retain store API).

**Comment by michaelklishin** [comment]
Done, has appropriate test coverage, self-QA'ed, collected useful feedback from user N.

Merging.

**Comment by bharatmca86** [comment]
Hi,
I have setup a three Node rabbitmq cluster with mqtt plugin enabled . All the nodes are in synch for every queues information but whenever I am publishing a message over a topic with 'retained' flag on , then in this case only the node to which I have connected , able to read out the last retained status of the client . But no other nodes from the cluster ,are able to read out the latest status . After reading out the documentation I came to know , we can achieve this through Cassandra or Riak based storage. But the problem is I am not an erlang developer so unable to configure this in my system . We are working here on IOT projects and using RabbitMQ throughout the organization . So I have two options , either I configure Cassandra/Radis as retained message storage and continue with RabbitMQ or I will go with EMQ which provides this kind of configuration. 

Please reply as I am stuck with this issue and not able to proceed with my other development tasks.

Regards,
Bharat

**Comment by michaelklishin** [comment]
Please use the RabbitMQ mailing list for questions. Retained messages are currently stored in a node-local store. This will likely change in the future but it is what it is today. There are other limitations around retained messages, too (#127, #154).
