### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by andye2004** [rabbitmq/rabbitmq-mqtt#160]
** {{badmatch,<<"T / HTTP/1.1\r\nHost: localhost:1883\r\nConnection: Upgrade\r\nPragma: no-c">>},
    [{rabbit_mqtt_frame,parse_frame,3,[]},
     {rabbit_mqtt_reader,process_received_bytes,2,[]},
     {gen_server2,handle_msg,2,[]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}

I don't know erlang at all and after having a look at the source I am none the wiser. Clearly my client application is not sending the appropriate details in the login message but I'm totally stumped as to what the problem is. Could anyone help?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
You pointed an HTTP client at the MQTT port. MQTT is a binary protocol and MQTT endpoints do not serve HTTP requests.

**Comment by andye2004** [comment]
Thanks @michaelklishin. Appreciate your help, I'm actually using MQTT.js so I'm guessing there must be some config somewhere I need to set.

**Comment by michaelklishin** [comment]
I cannot suggest much since you posted no code whatsoever. According to [mqtt.js docs](https://github.com/mqttjs/MQTT.js#connect) they support TCP and TLS connections as well as WebSocket ones. So presumably you want a `tcp://` URI or to use [Web MQTT](http://www.rabbitmq.com/web-mqtt.html) instead.

This is mailing list material (and mqtt.js mailing list more than RabbitMQ).

**Comment by andye2004** [comment]
@michaelklishin I really appreciate your help. Just before I saw this I'd manage to work out (with the help of a colleague) out that we were missing the web plugin. Hopefully I can get off and running now.

Again, thanks for your help!
