### ISSUE TITLE
RabbitMQ MQTT Plugin - MQTT Client ID ACL 

### ISSUE THREAD

**Issue by udkw93274** [rabbitmq/rabbitmq-mqtt#165]
Hi Dear. 

AWS support ACL to MQTT ClientID 
Example Client ID : test1023qos1 => set deny to connect
Example Client ID : test2092qos0 => set allow to connect

Also I want to support this client id(this is not same User name) ACL and i found https://www.rabbitmq.com/access-control.html#topic-authorisation
document explain this ACL supportting!

But short explain and no example so very hard for me.
 
How i set permission client id connection.

**Comment by lukebakken** [comment]
Thank you for your time and for using RabbitMQ.

The RabbitMQ team uses GitHub issues for specific actionable items engineers can work on. This means that GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, and so on.

Please post your question or issue to the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used.
 * Server logs.
 * A code example or terminal transcript that can be used to reproduce.
 * **Full** exception stack traces (not a single line message).
 * If applicable, `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output). Redirect output to files and attach the files to your message.
 * Other relevant information about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html).

Feel free to edit out hostnames and other potentially sensitive information.

If enough details and evidence are provided that demonstrate an issue we'd be happy to file one on GitHub.

Thanks again!
Luke

**Comment by michaelklishin** [comment]
Connection can only be denied if credentials are incorrect, anonymous connection is disabled or the user doesn't have any permissions for the target [virtual host](http://www.rabbitmq.com/vhosts.html). MQTT client ID is not a factor.
