### ISSUE TITLE
Clustering/Mirroring issue with MQTT

### ISSUE THREAD

**Issue by abhi-dwivedi** [rabbitmq/rabbitmq-mqtt#169]
Team

We are having issue with clustering/mirroring in rabbitmq with mqtt versions: 3.6.15 Erlang 19.3

So we where having data discrepancies while doing pub/sub in 2 node cluster.
Publish with retaining flag
One time we are getting another data while doing subscribe and next time we are doing subscribe we are getting different data on different client id.
Doing it from MQTTfx.

Even we enable the mirror also:
rabbitmqctl set_policy ha-all "" '{"ha-mode":"all","ha-sync-mode":"automatic"}'

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Retaining is currently node-local (#91, #127).
