### ISSUE TITLE
Retained message publishing does not translate dot topic separators (AMQP 0-9-1) to slashes (MQTT)

### ISSUE THREAD

**Issue by rsandbach** [rabbitmq/rabbitmq-mqtt#175]
I am working with a MQTT publisher that I cannot control the topic generated and am trying to understand better what the "will not work as expected" note in the documentation means. I'd be happy to update the documentation with some more detail.

The publisher uses slashes "/" and (dots) "." in the topic, so it is far from ideal.

While testing using web sockets (paho-mqtt client), I am observing something that I'm not sure is expected behavior or not. 

If I subscribe to the topic that the publisher is publishing to _**TESTING/Equipment.Download.Message**_ I receive the most recent value immediately after subscribing (with a message topic of _**TESTING/Equipment.Download.Message**_). However, subsequent values have the topic translated to _**TESTING/Equipment/Download/Message**_.

If I subscribe to TESTING/Equipment/Download/Message, I do NOT receive a value until a new message is published.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
MQTT topics are currently internally translated to those used by the topic exchange where the dot is the segment separator. See #58. Slashes are used for separators in MQTT and are translated to dots.

**Comment by michaelklishin** [comment]
As clarified on the mailing list, the issue here was with [re]publishing of retained messages. @rsandbach contributed a fix in #176.
