### ISSUE TITLE
Message holding user_id property

### ISSUE THREAD

**Issue by miili** [rabbitmq/rabbitmq-mqtt#205]
Hi there,

we are publishing to the MQTT endpoint and consume AMQP downstream. Is it intended behaviour that `user_id` and `timestamp` property are not set?

Best,
M

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
RabbitMQ does not set either of those fields. [rabbitmq_message_timestamp](https://github.com/rabbitmq/rabbitmq-message-timestamp) can set the timestamp. Username is [validated](https://www.rabbitmq.com/validated-user-id.html) but not set.

Neither of those fields exists in MQTT 3.1.1, so the behavior is what it is in AMQP 0-9-1 by default.
