### ISSUE TITLE
multiple vhost in rabbitmq

### ISSUE THREAD

**Issue by vigneshindn** [rabbitmq/rabbitmq-mqtt#211]
i have create a server for rabbitmq , now am facing issue in adding multiple vhost in rabbit mq and starting the service. I have full of error in my configuration so am not shared here. do anybody have done , please share me

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
We cannot suggest anything without **full** error messages, RabbitMQ and Erlang version information and node logs.
