### ISSUE TITLE
Client isn't being notified in case of unroutable publishes

### ISSUE THREAD

**Issue by EdwardSkrobala** [rabbitmq/rabbitmq-mqtt#222]
## Summary

Our team faced up with issue on our production environment - after RabbitMQ maintance all queues were deleted and our client is still publishing messages without any error. 
We've prepared a short Pub/Sub demo reproducing it (https://github.com/EdwardSkrobala/MqttIssue).

Publisher & Subscriber connect to broker via websockets, publisher sends message every 5 sec with Qos-1 level set.
We need publisher to be acknowledged if it publishes message that is not delivered to subscriber.

## Environment:
* .NET Core 3.0
* RabbitMQ 3.7
* Plugin: Mqtt
* Client Lib: MQTTnet (https://github.com/chkr1011/MQTTnet)

## Steps to reproduce:
* Run `docker-compose -f docker-compose-brokers.yml up` from root folder
* Run `dotnet run` from project folder (src/Test/)
* Trigger management UI - http://localhost:15672/#/queues (username="test", pass="test")
* Delete Queue `mqtt-subscription-subscriberqos1` to simulate maintance on server.

## Code lines showing issue
Message configuration
`var message = new MqttApplicationMessageBuilder()
                .WithTopic("MyTopic")
                .WithPayload($"Hello World [{DateTime.Now.ToLongTimeString()}]")
                .WithQualityOfServiceLevel(MQTTnet.Protocol.MqttQualityOfServiceLevel.AtLeastOnce)
                .WithRetainFlag(false)
                .Build()`
PublishAsync returns MqttClientPublishResult  containing MqttClientPublishReasonCode (https://github.com/chkr1011/MQTTnet/blob/master/Source/MQTTnet/Client/Publishing/MqttClientPublishResult.cs)
`var publishResult = await publisherClient.PublishAsync(message)`

**Expected result:**
Exception or MqttClientPublishResult.ReasonCode = MqttClientPublishReasonCode.NoMatchingSubscribers

**Actual result:**
MqttClientPublishResult.ReasonCode = Success

Thanks in advance for the assistance

**Comment by michaelklishin** [comment]
There is no feature in the MQTT 3.1.1 protocol that would notify publishers when a consumer (subscriber) delivery fails. Publisher-to-broker and broker-to-consumer communications are covered by [acknowledgments](https://www.rabbitmq.com/confirms.html) but end-to-end confirmations are up to your application.

The way publishes are acknowledged in MQTT 3.1.1 is [via PUBACK frames](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/csprd02/mqtt-v3.1.1-csprd02.html#_Toc385349773) and only if publishing is done using QoS 1 (QoS 0 means "at most once", so very loose guarantees).
Your code does enable "at least once" publishing.

Routing and queueing are [separate concepts](https://www.rabbitmq.com/publishers.html#protocols) in RabbitMQ. For MQTT plugin this means that a deleted queue would trigger a [consumer cancelation notification](https://www.rabbitmq.com/consumer-cancel.html). That is only relevant for consumers.

Publishers use a different mechanism covered in [Unroutable Message Handling](https://www.rabbitmq.com/publishers.html#unroutable). This plugin does use a publisher confirmation mechanism internally but does not handle publishes unroutable because there are no queues present. I will file a more detailed issue about that and reference this one.
